image: docker:latest

variables: 
  DOCKER_DRIVER: overlay

services:
  - docker:dind

before_script:
  - docker info
  - curl -L "https://github.com/docker/compose/releases/download/v2.2.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - chmod +x /usr/local/bin/docker-compose
  - export PATH=/usr/local/bin/:$PATH
  - echo $PATH

stages:
  - build
  - test

python-tests:
  stage: test
  script:
    - docker-compose up aisdb_test --build 
