stages:
  - build

before_script:
  - mkdir -p ~/ais && export DATA_DIR=~/ais
  - apk add --no-cache gcc python3
  - python3 -m ensurepip && python3 -m pip install --upgrade setuptools wheel

create-package:
  type: build
  stage: build
  only: 
    - test-ci
  script:
    - python3 -m pip install .
