image: meridiancfi/aisdb:latest

stages:
  - pkgbuild
  - rust-test
  - python-test
  - python-profile
  - build-website

pkgbuild:
  image: 
    name: ghcr.io/pyo3/maturin:main
    entrypoint: [""]
  stage: pkgbuild
  script:
    - maturin build --release --manylinux 2014 --strip
    - find ./target
  artifacts:
    paths:
      - ./target/wheels

rust-test:
  stage: rust-test
  script:
    - cargo test --color=always -- --nocapture

python-test:
  stage: python-test
  script:
    - find ./target/
    - export WHEEL="`ls -r1 ./target/wheels/aisdb-*cp310*.whl | head -n1`"
    - python -m pip install ${WHEEL} --force-reinstall
    - rm aisdb/__init__.py aisdb/tests/__init__.py
    - python -m coverage run -m pytest --color=yes --tb=native --doctest-modules -k "not marinetraffic" aisdb/tests/
    - python -m coverage report
  needs:
    - job: pkgbuild
      artifacts: true
  cache:
    key: persistent_000
    paths:
      - aisdb/tests/marinetraffic_test.db

#python-profile:
#  stage: python-profile
#  script:
#    - python -m cProfile -o profile '/usr/bin/python -m pytest'
#    - python -c "import pstats; p = pstats.Stats('profile'); p.strip_dirs(); p.sort_stats('tottime'); p.print_stats(50);"
#  cache:
#    key: persistent_000
#    paths:
#      - aisdb/tests/marinetraffic_test.db

build-website:
  stage: build-website
  only: 
    - master
  script:
    - cd aisdb_web && npm install
    - /bin/bash build_website.sh


  #  - rm -rf public && cp -r docs/html public
  #artifacts:
  #  paths:
  #    - public
  #cache:
  #  key: "$CI_COMMIT_REF_SLUG"
  #  paths:
  #    - public
