image: meridiancfi/aisdb:latest

stages:
  - pkgbuild
  - rust-test
  - python-test
  - python-profile
  - build-website

pkgbuild:
  image: 
    name: ghcr.io/pyo3/maturin:main
    entrypoint: [""]
  stage: pkgbuild
  script:
    - maturin build --release --manylinux 2014 --strip --interpreter 3.8 3.9 3.10
  artifacts:
    paths:
      - ./target/wheels

rust-test:
  stage: rust-test
  script:
    - cargo test --color=always -- --nocapture

python-test:
  stage: python-test
  script:
    #- export WHEEL="`ls -r1 ./target/wheels/aisdb-*cp310*.whl | head -n1`"
    #- python -m pip install ${WHEEL} --force-reinstall
    - python -m pytest aisdb/tests --durations=5
  #needs:
  #  - job: pkgbuild
  #    artifacts: true
  #coverage: '(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$'
  coverage: '/TOTAL.*\s+(\d+\%)/'
  cache:
    key: persistent_000
    paths:
      - testdata/*
      - aisdb_web/dist_coverage/

build-website:
  stage: build-website
  only: 
    - master
  script:
    - cd aisdb_web && npm install
    - /bin/bash build_website.sh
