default:
  image: matt24smith/aisdb

stages:
  - build

before_script:
  - pacman -S docker docker-compose
  #- echo test
  # push docker image to dockerhub
  # docker push matt24smith/aisdb:tagname
  #

create-package:
  type: build
  stage: build
  only: 
    - test-ci
    - submodule
