image: meridiancfi/aisdb:latest

stages:
  - pkgbuild
  - rust-test
  - python-test
  - build-website

pkgbuild:
  image: 
    name: ghcr.io/pyo3/maturin:main
    entrypoint: [""]
  stage: pkgbuild
  script:
    - maturin build --release --manylinux 2014
  artifacts:
    paths:
      - target/wheels/

rust-test:
  stage: rust-test
  script:
    - cargo test --release --color=always -- --nocapture

python-test:
  stage: python-test
  script:
    - python -m pip install .
    - python -m pytest --color=yes --tb=native --doctest-modules tests/ -k "not merge"

build-website:
  stage: build-website
  only: 
    - master
  script:
    - /bin/bash aisdb_web/build_website.sh
  #  - rm -rf public && cp -r docs/html public
  #artifacts:
  #  paths:
  #    - public
  #cache:
  #  key: "$CI_COMMIT_REF_SLUG"
  #  paths:
  #    - public
