#image:
#  name: docker/compose:1.29.2

#services:
#  - docker:dind

stages:
  - build
  - test
  - doctest

before_script:
  - mkdir -p ~/ais && export DATA_DIR=~/ais
  - apk add --no-cache gcc py3-pip python3
  - pip3 install --upgrade setuptools wheel

create-package:
  type: build
  stage: build
  only: 
    - test-ci
  script:
    - pip3 install .
