#image:
#  name: alpine:latest

stages:
  - build
  - test
  - doctest

before_script:
  - apk add git docker docker-compose
  - mkdir -p ~/ais
  - export DATA_DIR=~/ais
  - git clone https://gitlab.meridian.cs.dal.ca/matt_s/aisdb.git && cd aisdb

create-package:
  type: build
  stage: build
  only: 
    - test-ci
  script:
    - docker-compose build aisdb
