#image:
#  name: alpine:latest

stages:
  - build
  - test
  - doctest

before_script:
  - apk add docker docker-compose
  - docker-compose -v

create-package:
  type: build
  stage: build
  only: 
    - test-ci
  script:
    - echo testing
    - docker-compose -v
