image: meridiancfi/aisdb:latest

stages:
  - pkgbuild
  - rust-test
  - python-test
  - python-profile
  - build-website

pkgbuild:
  image: 
    name: ghcr.io/pyo3/maturin:main
    entrypoint: [""]
  stage: pkgbuild
  script:
    - maturin build --release --manylinux 2014 --strip --interpreter 3.8 3.9 3.10
  artifacts:
    paths:
      - ./target/

rust-test:
  stage: rust-test
  script:
    - cargo test --color=always -- --nocapture
  artifacts:
    paths:
      - ./testdata
      - ./target/

python-test:
  stage: python-test
  script:
    - [[ ! -d "env" ]] && python -m venv env
    - source env/bin/activate && python -m pip install --upgrade pip maturin
    - source env/bin/activate && maturin develop --release --extras=test,docs
    - mkdir -p data_dir
    - source env/bin/activate && AISDBDATADIR="./data_dir/" python -m pytest aisdb/tests/ --durations=5 -s -k 'not marinetraffic'
  coverage: '/TOTAL.*\s+(\d+\%)/'
  dependencies:
    - rust-test
  cache:
    key: persistent_000
    paths:
      - ./aisdb_web/dist_coverage/
      - ./data_dir
      - ./target/
      - ./testdata/
      - ./env
  artifacts:
    paths:
      - ./aisdb_web/dist_coverage/
      - ./data_dir
      - ./env
      - ./target
      - ./testdata

build-website:
  stage: build-website
  only: 
    - master
  dependencies:
    - python-test
  script:
    - cd aisdb_web && npm install
    - source ./env/bin/activate && /bin/bash build_website.sh
