default:
  image: docker/compose:latest
  #entrypoint: ["/bin/sh", "-c"]

services:
  - docker:dind

before_script:
  - service docker start
  #- sudo dockerd
  - docker version
  - docker-compose version

stages:
  - build

build image:
  stage: build
  script:
    - docker-compose up --build aisdb_base
