default:
  image: docker/compose:latest
  #entrypoint: ["/bin/sh", "-c"]

services:
  - docker:dind

before_script:
  - systemctl enable docker && systemctl start docker
  - docker version
  - docker-compose version

stages:
  - build
  - test
  - docs

build image:
  stage: build
  script:
    - docker-compose up --build aisdb_base
