#image:
#  name: alpine:latest

stages:
  - build
  - test
  - doctest

before_script:
  - mkdir -p ~/ais && export DATA_DIR=~/ais
  - apk add docker docker-compose 

create-package:
  type: build
  stage: build
  only: 
    - test-ci
  script:
    - docker-compose build aisdb
