#image:
#  name: alpine:latest

stages:
  - build
  - test
  - doctest

before_script:
  - apk update
  - apk add git docker docker-compose openrc
  - service docker start
  - rc-update add docker boot
  - service docker status
  - mkdir -p ~/ais && export DATA_DIR=~/ais

create-package:
  type: build
  stage: build
  only: 
    - test-ci
  script:
    - docker-compose build aisdb
