image: meridiancfi/aisdb:latest

stages:
  - rust-build
  - python-build
  - rust-test
  - python-test
  - docs

rust-build:
  stage: rust-build
  script:
    - cargo build --manifest-path=/home/ais_env/aisdb_rust/Cargo.toml --release

python-build:
  stage: python-build
  script:
    - python -m pip install .

rust-test:
  stage: rust-test
  script:
    - cargo test --manifest-path=/home/ais_env/aisdb_rust/Cargo.toml --release --color=always -- --nocapture

# skip tests requiring a desktop environment or web data sources
python-test:
  stage: python-test
  script:
    - python -m pip install .
    - python -m pytest --color=yes --tb=native --doctest-modules tests/ -k "not merge"

docs:
  stage: docs
  only: 
    - master
  script:
    - /bin/bash docs/sphinxbuild.sh
    - rm -rf public && cp -r docs/html public
  artifacts:
    paths:
      - public
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - public
