image: meridiancfi/aisdb:latest

stages:
  - pkgbuild
  - rust-test
  - python-test
  - python-profile
  - build-website

pkgbuild:
  image: 
    name: ghcr.io/pyo3/maturin:main
    entrypoint: [""]
  stage: pkgbuild
  script:
    - maturin build --release --manylinux 2014 --strip --interpreter 3.8 3.9 3.10
  artifacts:
    paths:
      - ./target/wheels

rust-test:
  stage: rust-test
  script:
    - cargo test --color=always -- --nocapture

python-test:
  stage: python-test
  script:
    - python -m venv env
    - source env/bin/activate && python -m pip install --upgrade maturin pytest pytest-cov pytest-asyncio
    - source env/bin/activate && maturin develop --release --extras=test,docs
    - source env/bin/activate && python -m pytest aisdb/tests/ --durations=5
  #coverage: '(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$'
  coverage: '/TOTAL.*\s+(\d+\%)/'
  cache:
    key: persistent_000
    paths:
      - testdata/*
      - aisdb_web/dist_coverage/

build-website:
  stage: build-website
  only: 
    - master
  script:
    - cd aisdb_web && npm install
    - /bin/bash build_website.sh
