image:
  name: docker:latest

services:
  - docker:dind

stages:
  - build
  - test
  - doctest

before_script:
#  - mkdir -p ~/ais && export DATA_DIR=~/ais
  - apk add --no-cache py3-pip && pip install docker-compose

create-package:
  type: build
  stage: build
  only: 
    - test-ci
  script:
    - docker-compose build aisdb
