[package]
version = "1.4.40"
name = "aisdb"
edition = "2021"
include = [ "aisdb/*.py", "aisdb/aisdb_sql", "aisdb/database/*.py", "aisdb/webdata/*.py", "/src", "pyproject.toml",]

[lib]
crate-type = [ "cdylib", "rlib",]
path = "src/lib.rs"

[dependencies]
geo = "0.23.0"
geo-types = "*"
nmea-parser = "0.10"

[dependencies.aisdb-lib]
path = "aisdb_lib"

[dependencies.aisdb-receiver]
path = "receiver"

[dependencies.pyo3]
version = "0.17.3"
features = [ "extension-module", "generate-import-lib",]
