[package]
version = "1.6.6"
name = "aisdb"
edition = "2021"
include = [ "aisdb/*.py", "aisdb/aisdb_sql", "aisdb/database/*.py", "aisdb/webdata/*.py", "/src", "pyproject.toml", "aisdb_web/dist_map/index.html", "aisdb_web/dist_map/favicon.svg", "aisdb_web/dist_map/favicon.png", "aisdb_web/dist_map/assets/*", "aisdb_web/dist_map_bingmaps/index.html", "aisdb_web/dist_map_bingmaps/favicon.svg", "aisdb_web/dist_map_bingmaps/favicon.png", "aisdb_web/dist_map_bingmaps/assets/*",]

[lib]
crate-type = [ "cdylib", "rlib",]
path = "src/lib.rs"

[dependencies]
geo = "0.25"
geo-types = "*"
nmea-parser = "0.10"

[build-dependencies]
wasm-opt = "0.112"
wasm-pack = "0.11"
reqwest = "0.11"

[dependencies.aisdb-lib]
path = "aisdb_lib"
features = [ "sqlite", "postgres",]

[dependencies.aisdb-receiver]
path = "receiver"

[dependencies.pyo3]
version = "0.18.3"
features = [ "extension-module", "generate-import-lib",]
