[package]
version = "1.3.129"
name = "aisdb"
authors = [ "MERIDIAN // Matt Smith matthew.smith@dal.ca",]
edition = "2021"
include = [ "/aisdb/*.py", "/aisdb/aisdb_sql", "/aisdb/database/*.py", "/aisdb/tests", "/aisdb/webdata/*.py", "/src", "pyproject.toml",]
build = "build.rs"
readme = "readme.rst"
description = "AIS Database and Processing Utils"
homepage = "https://aisdb.meridian.cs.dal.ca/"
documentation = "https://aisdb.meridian.cs.dal.ca/doc/readme.html"
repository = "https://gitlab.meridian.cs.dal.ca/public_projects/aisdb/"
license-file = "license.txt"

[lib]
crate-type = [ "cdylib", "rlib",]
path = "src/lib.rs"

[dependencies]
geo = "0.20.1"
geo-types = "*"
include_dir = "0.7.2"

[dependencies.chrono]
version = "0.4.21"

[dependencies.csv]
version = "1.1"

[dependencies.nmea-parser]
version = "0.9"

[dependencies.pico-args]
version = "0.4.2"
features = [ "eq-separator",]

[dependencies.pyo3]
version = "0.16.4"
features = [ "extension-module",]

[dependencies.rusqlite]
version = "0.27"

[profile.release]
lto = true
opt-level = 3
