version: '3.9'


services:

  aisdb:
    container_name: aisdb_sshd
    build: 
      target: sshhost
      context: .
      args:
        - USERNAME=ais_env
    expose:
      - "22"
    secrets:
      - host_ssh_key
      - host_authorized_keys
    volumes:
      - ${DATA_DIR}:/home/ais_env/ais

  docs:
    container_name: aisdb_docs
    build: 
      target: webserv
      context: .
      args:
        - USERNAME=ais_env
    expose:
      - "8085"
    networks:
      - net1

  test:
    container_name: aisdb_test
    build:
      target: runtest
      context: .
      args:
        - USERNAME=ais_env
    volumes:
      - ${DATA_DIR}:/home/ais_env/ais


secrets:
  host_ssh_key:
    file: ~/.ssh/id_aisdb
  host_authorized_keys:
    file: ~/.ssh/id_aisdb.pub


networks:
  net1:
    name: net1
    enable_ipv6: true
    ipam:
      config:
        - subnet: "2001:3984:3989::/64"
          gateway: "2001:3984:3989::1"

