version: '3.9'

services:

  # compile rust target and run rust tests
  aisdb_rust:
    container_name: aisdb_rust
    environment:
      - RUST_BACKTRACE=1
    build:
      target: test_rust
      context: .
      dockerfile: ./docker/Dockerfile
    environment:
      - RUST_BACKTRACE=1
    networks:
      ipv6_private:
        ipv6_address: "fc00::4"

  # build python package and run python tests
  aisdb_test:
    container_name: aisdb_test
    build:
      target: test_python
      context: .
      dockerfile: ./docker/Dockerfile
    environment:
      - RUST_BACKTRACE=1
    networks:
      ipv6_private:
        ipv6_address: "fc00::5"

  # nodeJS docs server + webapp
  aisdb_web:
    container_name: aisdb_web
    build: 
      target: webserv
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        BINGMAPSKEY: ${BINGMAPSKEY:-"Your Bing Maps Key from https://www.bingmapsportal.com/ here"}
        AISDBHOST: ${AISDBHOST:-127.0.0.1}
        AISDBPORT: ${AISDBPORT:-9924}
    #expose:
    #  - "8080"
    depends_on:
      - nginx
      #- certbot
    networks:
      ipv6_private:
        ipv6_address: "fc00::3"

  # database server
  aisdb_websocket:
    container_name: aisdb_websocket
    build:
      target: build_python
      context: .
      dockerfile: ./docker/Dockerfile
    environment:
      AISDBHOSTALLOW: ${AISDBHOSTALLOW:-*}
      AISDBPORT: ${AISDBPORT:-9924}
    #expose:
    #  - "9924"
    command:
      ['python', 'aisdb/mapsocket.py']
    networks: 
      ipv6_private:
        ipv6_address: "fc00::6"

  # reverse proxy router
  nginx:
    image: nginx:latest
    container_name: aisdb_nginx
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
      # - ./nginx/certbot/conf:/etc/letsencrypt
      # - ./nginx/certbot/www:/var/www/certbot
    ports:
     - "80:80"
     - "443:443"
     - "9924:9924"
    networks:
      ipv6_private:
        ipv6_address: "fc00::2"

  #certbot:
  #image: certbot/certbot
  #container_name: aisdb_certbot
  #volumes:
  #  - ./nginx/certbot/conf:/etc/letsencrypt
  #  - ./nginx/certbot/www:/var/www/certbot
  #networks:
  #  ipv6_private:
  #    ipv6_address: "fc00::4"


networks:
  ipv6_private:
    name: ipv6_private
    enable_ipv6: true
    ipam:
      config:
        - subnet: "fc00:0:0::/119"
          gateway: "fc00:0:0::1"

