version: '3.9'

#
# show files not covered by dockerignore
# useful for debugging large build context
# find . | grep -vi "`cat .dockerignore`" 
#
#


services:

  aisdb_sshd:
    container_name: aisdb_sshd
    build: 
      target: sshhost
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        - USERNAME=ais_env
    expose:
      - "22"
    secrets:
      - host_ssh_key
      - host_authorized_keys
    volumes:
      - ${DATA_DIR}:/home/ais_env/ais
    networks:
      - ipv6_private 

  aisdb_docs:
    container_name: aisdb_docs
    build: 
      target: webserv
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        - USERNAME=ais_env
    expose:
      - "8085"
    networks:
      - ipv6_private

  aisdb_rust:
    container_name: aisdb_rust
    environment:
      - RUST_BACKTRACE=1
    build:
      target: compile
      context: .
      dockerfile: ./docker/Dockerfile
      args:
          - USERNAME=ais_env
    #volumes:
    #  - ${DATA_DIR}:/home/ais_env/ais
    networks:
      - ipv6_private

  aisdb_test:
    container_name: aisdb_test
    build:
      target: runtest
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        - USERNAME=ais_env
    #volumes:
    #  - ${DATA_DIR}:/home/ais_env/ais
    networks:
      - ipv6_private


secrets:
  host_ssh_key:
    file: ~/.ssh/id_aisdb
  host_authorized_keys:
    file: ~/.ssh/id_aisdb.pub


networks:
  ipv6_private:
    name: ipv6_private
    enable_ipv6: true
    ipam:
      config:
        - subnet: "fc00:0:0::/120"
          gateway: "fc00:0:0::1"

