version: '3.9'

secrets:
  host_ssh_key:
    file: ~/.ssh/id_aisdb
  host_authorized_keys:
    file: ~/.ssh/id_aisdb.pub

services:
  test:
    container_name: aisdb
    #environment:
    #  QT_DEBUG_PLUGINS: 1
    #  QT_QPA_PLATFORM: offscreen
    #  QT_PLUGIN_PATH: /usr/lib/qt/plugins
    #  XDG_RUNTIME_DIR: /tmp/runtime-ais_env
    build: 
      context: .
      args:
        - USERNAME=ais_env
    expose:
      - "22"
    secrets:
      - host_ssh_key
      - host_authorized_keys
    volumes:
      - ${DATA_DIR}:/home/ais_env/ais

