version: '3.9'

services:

  aisdb_rust:
    container_name: aisdb_rust
    environment:
      - RUST_BACKTRACE=1
    build:
      target: test_rust
      context: .
      dockerfile: ./docker/Dockerfile
    environment:
      - RUST_BACKTRACE=1
    networks:
      - ipv6_private

  aisdb_test:
    container_name: aisdb_test
    build:
      target: test_python
      context: .
      dockerfile: ./docker/Dockerfile
    environment:
      - RUST_BACKTRACE=1
    networks:
      - ipv6_private

  aisdb_web:
    container_name: aisdb_web
    build: 
      target: webserv
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        BINGMAPSKEY: ${BINGMAPSKEY:-"Your Bing Maps Key from https://www.bingmapsportal.com/ here"}
    expose:
      - "8080"
    depends_on:
      - nginx
      #- certbot
    networks:
      ipv6_private:
        ipv6_address: "fc00::3"

  nginx:
    image: nginx:latest
    container_name: aisdb_nginx
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
      # - ./nginx/certbot/conf:/etc/letsencrypt
      # - ./nginx/certbot/www:/var/www/certbot
    ports:
     - "80:80"
     - "443:443"
    networks:
      ipv6_private:
        ipv6_address: "fc00::2"

  #certbot:
  #image: certbot/certbot
  #container_name: aisdb_certbot
  #volumes:
  #  - ./nginx/certbot/conf:/etc/letsencrypt
  #  - ./nginx/certbot/www:/var/www/certbot
  #networks:
  #  ipv6_private:
  #    ipv6_address: "fc00::4"


networks:
  ipv6_private:
    name: ipv6_private
    enable_ipv6: true
    ipam:
      config:
        - subnet: "fc00:0:0::/119"
          gateway: "fc00:0:0::1"

