version: '3.9'

services:

  aisdb_rust:
    container_name: aisdb_rust
    environment:
      - RUST_BACKTRACE=1
    build:
      target: test_rust
      context: .
      dockerfile: ./docker/Dockerfile
    environment:
      - RUST_BACKTRACE=1
    networks:
      - ipv6_private

  aisdb_test:
    container_name: aisdb_test
    build:
      target: test_python
      context: .
      dockerfile: ./docker/Dockerfile
    environment:
      - RUST_BACKTRACE=1
    networks:
      - ipv6_private

  aisdb_docs:
    container_name: aisdb_docs
    build: 
      target: webserv
      context: .
      dockerfile: ./docker/Dockerfile
    environment:
      - VITE_BINGMAPSKEY='Your Bing Maps Key from https://www.bingmapsportal.com/ here'
    expose:
      - "8085"
    networks:
      ipv6_private:
        ipv6_address: "fc00::3"
    #ports:
    #  - "80:8085"

  aisdb_sshd:
    container_name: aisdb_sshd
    build: 
      target: sshhost
      context: .
      dockerfile: ./docker/Dockerfile
    expose:
      - "22"
    secrets:
      - host_ssh_key
      - host_authorized_keys
    networks:
      ipv6_private:
        ipv6_address: "fc00::4"

  nginx:
    image: nginx:latest
    container_name: aisdb_nginx
    volumes:
      - ./nginx/aisdb.conf:/etc/nginx/nginx.conf:ro
      # - ./nginx/certbot/conf:/etc/letsencrypt
      # - ./nginx/certbot/www:/var/www/certbot
    ports:
     - "80:80"
     - "443:443"
    networks:
      ipv6_private:
        ipv6_address: "fc00::2"

  #certbot:
  #image: certbot/certbot
  #container_name: aisdb_certbot
  #volumes:
  #  - ./nginx/certbot/conf:/etc/letsencrypt
  #  - ./nginx/certbot/www:/var/www/certbot
  #networks:
  #  ipv6_private:
  #    ipv6_address: "fc00::4"


secrets:
  host_ssh_key:
    file: ~/.ssh/id_aisdb
  host_authorized_keys:
    file: ~/.ssh/id_aisdb.pub


networks:
  ipv6_private:
    name: ipv6_private
    enable_ipv6: true
    ipam:
      config:
        - subnet: "fc00:0:0::/119"
          gateway: "fc00:0:0::1"

