version: '3.9'

secrets:
  host_ssh_key:
    file: ~/.ssh/id_aisdb
  host_authorized_keys:
    file: ~/.ssh/id_aisdb.pub

services:
  test:
    container_name: aisdb
    env_file:
      - ~/.config/ais.cfg
    environment:
      QT_DEBUG_PLUGINS: 1
      QT_QPA_PLATFORM: offscreen
    build: 
      context: .
      args:
        - USERNAME=ais_env
    expose:
      - "22"
    secrets:
      - host_ssh_key
      - host_authorized_keys
    volumes:
      - ${DATA_DIR}:/home/ais_env/ais
      #- /run/media/matt/My Passport/:/home/ais_env/ais

