version: '3.9'


services:

  app:
    container_name: aisdb
    build: 
      target: sshhost
      context: .
      args:
        - USERNAME=ais_env
    expose:
      - "22"
    secrets:
      - host_ssh_key
      - host_authorized_keys
    volumes:
      - ${DATA_DIR}:/home/ais_env/ais

  tests:
    container_name: aisdb_test
    build:
      target: runtest
      context: .
      args:
        - USERNAME=ais_env

  docs:
    container_name: aisdb_docs
    build: 
      target: webserv
      context: .
      args:
        - USERNAME=ais_env
    expose:
      - "8085"


secrets:
  host_ssh_key:
    file: ~/.ssh/id_aisdb
  host_authorized_keys:
    file: ~/.ssh/id_aisdb.pub
