version: '3.9'

services:

  # compile rust targets and assemble python package wheels with maturin
  pkgbuild:
    container_name: pkgbuild
    image: ghcr.io/pyo3/maturin:main
    volumes:
      - ./:/io
    command: build --release --manylinux 2014 --strip  --interpreter 3.8 3.9 3.10

  # run rust tests
  rust-test:
    container_name: rust-test
    environment:
      - RUST_BACKTRACE=1
    build:
      target: aisdb
      context: .
      dockerfile: ./docker/Dockerfile
    environment:
      - RUST_BACKTRACE=1
    volumes:
      - ./Cargo.toml:/home/ais_env/Cargo.toml
      - ./src:/home/ais_env/src
      - ./build.rs:/home/ais_env/build.rs
      - ./testdata:/home/ais_env/testdata
      - ./target/:/home/ais_env/target
    command:
      ["cargo", "test", "--lib", "--release", "--color=always"]

  # build python package and run python tests
  python-test:
    container_name: python-test
    build:
      target: aisdb
      context: .
      dockerfile: ./docker/Dockerfile
    environment:
      - RUST_BACKTRACE=1
      - AISDBDATADIR=/home/ais_env/ais
      - AISDBTESTDIR=/home/ais_env/testdata
    volumes:
      - ${AISDBDATADIR:-/home/$USER/ais/}:/home/ais_env/ais/
      - ./aisdb_web/dist_coverage/:/home/ais_env/aisdb_web/dist_coverage/
      - ./target/:/home/ais_env/target
      - ./testdata:/home/ais_env/testdata
    init: true
    command: 
      ["python", "-m", "pytest", "aisdb/tests/", "aisdb/", "aisdb/database/", "aisdb/webdata/",  "--doctest-modules", "--durations=10", "-k", "not timing"]

  # nodeJS docs server + webapp
  webserver:
    container_name: webserver
    build: 
      target: webserv
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        BINGMAPSKEY: ${BINGMAPSKEY:-"Your Bing Maps Key from https://www.bingmapsportal.com/ here"}
        AISDBHOST: ${AISDBHOST:-127.0.0.1}
        AISDBPORT: ${AISDBPORT:-9924}
    command:
      ['npm', '--prefix', 'aisdb_web/', 'start']
    networks:
      ipv6_private:
        ipv6_address: "fc00::3"

  # nodejs docs server
  docserver:
    container_name: docserver
    build:
      target: docserv
      context: .
      dockerfile: ./docker/Dockerfile
    command:
      ['npm', '--prefix', 'aisdb_web/', 'run', 'doc']
    networks:
      ipv6_private:
        ipv6_address: "fc00::4"

  # database server
  websocket:
    container_name: websocket
    build:
      target: aisdb
      context: .
      dockerfile: ./docker/Dockerfile
    environment:
      AISDBHOST: ${AISDBHOST:-127.0.0.1}
      AISDBHOSTALLOW: ${AISDBHOSTALLOW:-*}
      AISDBPORT: ${AISDBPORT:-9924}
      # consider mounting volumes at the following locations
      AISDBPATH: '/home/ais_env/ais/ais.db'
      AISDBZONES: '/home/ais_env/ais/zones/'
      AISDBMARINETRAFFIC: '/home/ais_env/ais/marinetraffic.db'
      #AISDBDATADIR: '/home/ais_env/ais/'
      #AISDBTESTDIR: '/home/ais_env/testdata'
    init: true
    command: 
      ["python", "-u", "examples/start_websocket.py"]
    networks: 
      ipv6_private:
        ipv6_address: "fc00::6"

  # proxy router
  nginx:
    image: nginx:latest
    container_name: nginx
    environment: 
      AISDBHOST: ${AISDBHOST:-127.0.0.1}
      AISDBPORT: ${AISDBPORT:-9924}
    ports:
     - "80:80"
     - "443:443"
     - "${AISDBPORT:-9924}:${AISDBPORT:-9924}"
    networks:
      ipv6_private:
        ipv6_address: "fc00::2"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/templates/nginx.conf.template:ro
    # add something like the following to docker-compose.override.yml for SSL
    #  - ~/cert/conf:/etc/letsencrypt
    init: true
    command:
      ["/bin/sh" , "-c" , "envsubst '$${AISDBHOST} $${AISDBPORT}' < /etc/nginx/templates/nginx.conf.template > /etc/nginx/nginx.conf && while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g 'daemon off;' -c /etc/nginx/nginx.conf"]

  # https://eff-certbot.readthedocs.io/en/stable/using.html#where-are-my-certificates
  certbot:
    image: certbot/certbot
    container_name: certbot
    # add something like the following to docker-compose.override.yml for SSL
    #volumes:
    #  - ~/cert/conf:/etc/letsencrypt
    networks:
      ipv6_private:
        ipv6_address: "fc00::5"
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    depends_on:
      - nginx


networks:
  ipv6_private:
    name: ipv6_private
    enable_ipv6: true
    ipam:
      config:
        - subnet: "fc00:0:0::/119"
          gateway: "fc00:0:0::1"

