[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
socket_dispatch = { path = "../socket_dispatch" }

[dependencies.pico-args]
version = "0.5.0"
features = [ "eq-separator",]

[dev-dependencies]
server = {path = "../server"}
testconfig = {path = "../testconfig"}
