#!/usr/bin/python
'''
Automates version incrementing when a commit is added.
Copy this file to .git/hooks/ to enable versioning.
'''

import os
import subprocess

from packaging import version


projdir = subprocess.check_output(
            'git rev-parse --show-toplevel'.split()
            ).decode().rstrip()

# parse package version
versionfilepath = os.path.join(projdir, 'aisdb', 'version.py')
with open(versionfilepath, 'r') as f:
    exec(f.read())
v = version.Version(__version__)

# increment version number
bump = f'{v.major}.{v.minor}.{v.micro+1}'
bumpv = f'__version__ = "{bump}"\n'
print(f'\nbumping package version:\t{bumpv}\n')

# update aisdb/version.py
with open(versionfilepath, 'w') as f:
    f.write(bumpv)

# add to commit
cmd = 'git add aisdb/version.py'.split()
subprocess.run(cmd, check=True)
#os.system('git commit')
