#!/usr/bin/python
'''
Automated version incrementing whenever a commit is added.
Copy this file to .git/hooks/ to enable versioning.

Add 'version:major' or 'version:minor' to the commit message to bump the
version accordingly. Defaults to incrementing version patch level
'''

import os
import sys
import subprocess

from packaging import version

import aisdb

print(sys.argv)
commitmessagefile = sys.argv[1]
commitsource = sys.argv[2]
sha1checksum = sys.argv[3]
v = version.Version(aisdb.__version__)

with open(commitmessagefile, 'r') as f:
    commitmessage = f.read()

# parse commit message
if 'version:major' in commitmessage.lower():
    bump = f'{v.major+1}.0.0'
elif 'version:minor' in commitmessage.lower():
    bump = f'{v.major}.{v.minor+1}.0'
else:
    bump = f'{v.major}.{v.minor}.{v.micro+1}'
bumpv = f'__version__ = "{bump}"\n'
print(f'\nbumping package version:\t{bumpv}\n')

# parse package version
projdir = subprocess.check_output(
            'git rev-parse --show-toplevel'.split()
            ).decode().rstrip()

# update aisdb/version.py
versionfilepath = os.path.join(projdir, 'aisdb', 'version.py')
with open(versionfilepath, 'w') as f:
    f.write(bumpv)

# update changelog
changelogpath = os.path.join(projdir, 'changelog.rst')
if os.path.isfile(changelogpath):
    with open(changelogpath, 'r') as f:
        log = f.readlines()[3:]
else:
    log = []

header = '''
Changelog
=========
'''

changes = f'''
v{bump}
------

{commitmessage}
'''

newchangelog = header + changes + '\n'.join(log)

with open(changelogpath, 'w') as f:
    f.write(newchangelog)

# add the new version file to commit 
subprocess.run('''
    git
        --git-dir={projdir}
        --work-tree={projdir}
        add ./aisdb/version.py
        add ./changelog.rst
'''.split())

