SHORT_NAMES_TO_VARIABLES = {'100u': '100m_u_component_of_wind', '100v': '100m_v_component_of_wind', 'u10n': '10m_u_component_of_neutral_wind', 
               '10u': '10m_u_component_of_wind', 'v10n': '10m_v_component_of_neutral_wind', '10v': '10m_v_component_of_wind', 
               '10fg': '10m_wind_gust_since_previous_post_processing', '2d': '2m_dewpoint_temperature', '2t': '2m_temperature', 
               'rhoao': 'air_density_over_the_oceans', 'anor': 'angle_of_sub_gridscale_orography', 'isor': 'anisotropy_of_sub_gridscale_orography', 
               'bfi': 'benjamin_feir_index', 'bld': 'boundary_layer_dissipation', 'blh': 'boundary_layer_height', 'chnk': 'charnock', 
               'cdir': 'clear_sky_direct_solar_radiation_at_surface', 'cbh': 'cloud_base_height', 'cdww': 'coefficient_of_drag_with_waves', 
               'cape': 'convective_available_potential_energy', 'cin': 'convective_inhibition', 'cp': 'convective_precipitation', 
               'crr': 'convective_rain_rate', 'csf': 'convective_snowfall', 'csfr': 'convective_snowfall_rate_water_equivalent', 
               'uvb': 'downward_uv_radiation_at_the_surface', 'dctb': 'duct_base_height', 'lgws': 'eastward_gravity_wave_surface_stress', 
               'ewss': 'eastward_turbulent_surface_stress', 'e': 'evaporation', 'fal': 'forecast_albedo', 'flsr': 'forecast_logarithm_of_surface_roughness_for_heat', 
               'fsr': 'forecast_surface_roughness', 'cc': 'fraction_of_cloud_cover', 'wstar': 'free_convective_velocity_over_the_oceans', 'zust': 'friction_velocity', 
               'z': 'geopotential_at_surface', 'gwd': 'gravity_wave_dissipation', 'hcc': 'high_cloud_cover', 'cvh': 'high_vegetation_cover', 
               'istl1': 'ice_temperature_layer_1', 'istl2': 'ice_temperature_layer_2', 'istl3': 'ice_temperature_layer_3', 'istl4': 'ice_temperature_layer_4', 
               'i10fg': 'instantaneous_10m_wind_gust', 'iews': 'instantaneous_eastward_turbulent_surface_stress', 
               'ilspf': 'instantaneous_large_scale_surface_precipitation_fraction', 'ie': 'instantaneous_moisture_flux', 
               'inss': 'instantaneous_northward_turbulent_surface_stress', 'ishf': 'instantaneous_surface_sensible_heat_flux', 'kx': 'k_index', 
               'lblt': 'lake_bottom_temperature', 'cl': 'lake_cover', 'dl': 'lake_depth', 'licd': 'lake_ice_depth', 'lict': 'lake_ice_temperature', 
               'lmld': 'lake_mix_layer_depth', 'lmlt': 'lake_mix_layer_temperature', 'lshf': 'lake_shape_factor', 'ltlt': 'lake_total_layer_temperature', 
               'lsm': 'land_sea_mask', 'lsp': 'large_scale_precipitation', 'lspf': 'large_scale_precipitation_fraction', 'lsrr': 'large_scale_rain_rate', 
               'lsf': 'large_scale_snowfall', 'lssfr': 'large_scale_snowfall_rate_water_equivalent', 'lai_hv': 'leaf_area_index_high_vegetation', 
               'lai_lv': 'leaf_area_index_low_vegetation', 'lcc': 'low_cloud_cover', 'cvl': 'low_vegetation_cover', 
               'mx2t': 'maximum_2m_temperature_since_previous_post_processing', 'hmax': 'maximum_individual_wave_height', 
               'mxtpr': 'maximum_total_precipitation_rate_since_previous_post_processing', 'avg_ibld': 'mean_boundary_layer_dissipation', 
               'avg_cpr': 'mean_convective_precipitation_rate', 'avg_csfr': 'mean_convective_snowfall_rate', 'mdts': 'mean_direction_of_total_swell', 
               'mdww': 'mean_direction_of_wind_waves', 'avg_iegwss': 'mean_eastward_gravity_wave_surface_stress', 'avg_iews': 'mean_eastward_turbulent_surface_stress', 
               'erate': 'mean_evaporation_rate', 'avg_igwd': 'mean_gravity_wave_dissipation', 'avg_ilspf': 'mean_large_scale_precipitation_fraction', 
               'avg_lsprate': 'mean_large_scale_precipitation_rate', 'avg_lssfr': 'mean_large_scale_snowfall_rate', 
               'avg_ingwss': 'mean_northward_gravity_wave_surface_stress', 'avg_inss': 'mean_northward_turbulent_surface_stress', 'mpts': 'mean_period_of_total_swell', 
               'mpww': 'mean_period_of_wind_waves', 'avg_pevr': 'mean_potential_evaporation_rate', 'avg_rorwe': 'mean_runoff_rate', 'msl': 'mean_sea_level_pressure', 
               'avg_esrwe': 'mean_snow_evaporation_rate', 'avg_tsrwe': 'mean_snowfall_rate', 'avg_smr': 'mean_snowmelt_rate', 'msqs': 'mean_square_slope_of_waves', 
               'avg_ssurfror': 'mean_sub_surface_runoff_rate', 'avg_sdirswrf': 'mean_surface_direct_short_wave_radiation_flux', 
               'avg_sdirswrfcs': 'mean_surface_direct_short_wave_radiation_flux_clear_sky', 'avg_sdlwrf': 'mean_surface_downward_long_wave_radiation_flux', 
               'avg_sdlwrfcs': 'mean_surface_downward_long_wave_radiation_flux_clear_sky', 'avg_sdswrf': 'mean_surface_downward_short_wave_radiation_flux', 
               'avg_sdswrfcs': 'mean_surface_downward_short_wave_radiation_flux_clear_sky', 'avg_sduvrf': 'mean_surface_downward_uv_radiation_flux', 
               'avg_slhtf': 'mean_surface_latent_heat_flux', 'avg_snlwrf': 'mean_surface_net_long_wave_radiation_flux', 
               'avg_snlwrfcs': 'mean_surface_net_long_wave_radiation_flux_clear_sky', 'avg_snswrf': 'mean_surface_net_short_wave_radiation_flux', 
               'avg_snswrfcs': 'mean_surface_net_short_wave_radiation_flux_clear_sky', 'avg_surfror': 'mean_surface_runoff_rate', 
               'avg_ishf': 'mean_surface_sensible_heat_flux', 'avg_tdswrf': 'mean_top_downward_short_wave_radiation_flux', 
               'avg_tnlwrf': 'mean_top_net_long_wave_radiation_flux', 'avg_tnlwrfcs': 'mean_top_net_long_wave_radiation_flux_clear_sky', 
               'avg_tnswrf': 'mean_top_net_short_wave_radiation_flux', 'avg_tnswrfcs': 'mean_top_net_short_wave_radiation_flux_clear_sky', 
               'avg_tprate': 'mean_total_precipitation_rate', 'dndza': 'mean_vertical_gradient_of_refractivity_inside_trapping_layer', 
               'avg_vimdf': 'mean_vertically_integrated_moisture_divergence', 'mwd': 'mean_wave_direction', 'mwd1': 'mean_wave_direction_of_first_swell_partition', 
               'mwd2': 'mean_wave_direction_of_second_swell_partition', 'mwd3': 'mean_wave_direction_of_third_swell_partition', 'mwp': 'mean_wave_period', 
               'mp1': 'mean_wave_period_based_on_first_moment', 'p1ps': 'mean_wave_period_based_on_first_moment_for_swell', 
               'p1ww': 'mean_wave_period_based_on_first_moment_for_wind_waves', 'p2ps': 'mean_wave_period_based_on_second_moment_for_swell', 
               'p2ww': 'mean_wave_period_based_on_second_moment_for_wind_waves', 'mwp1': 'mean_wave_period_of_first_swell_partition', 
               'mwp2': 'mean_wave_period_of_second_swell_partition', 'mwp3': 'mean_wave_period_of_third_swell_partition', 'mp2': 'mean_zero_crossing_wave_period', 
               'mcc': 'medium_cloud_cover', 'mn2t': 'minimum_2m_temperature_since_previous_post_processing', 
               'mntpr': 'minimum_total_precipitation_rate_since_previous_post_processing', 'dndzn': 'minimum_vertical_gradient_of_refractivity_inside_trapping_layer', 
               'wmb': 'model_bathymetry', 'alnid': 'near_ir_albedo_for_diffuse_radiation', 'alnip': 'near_ir_albedo_for_direct_radiation', 
               'phioc': 'normalized_energy_flux_into_ocean', 'phiaw': 'normalized_energy_flux_into_waves', 'tauoc': 'normalized_stress_into_ocean', 
               'mgws': 'northward_gravity_wave_surface_stress', 'nsss': 'northward_turbulent_surface_stress', 
               'dwi': 'ocean_surface_stress_equivalent_10m_neutral_wind_direction', 'wind': 'ocean_surface_stress_equivalent_10m_neutral_wind_speed', 
               'o3': 'ozone_mass_mixing_ratio', 'pp1d': 'peak_wave_period', 'tmax': 'period_corresponding_to_maximum_individual_wave_height', 
               'pev': 'potential_evaporation', 'pv': 'potential_vorticity', 'ptype': 'precipitation_type', 'ro': 'runoff', 'siconc': 'sea_ice_cover', 
               'sst': 'sea_surface_temperature', 'swh': 'significant_height_of_combined_wind_waves_and_swell', 'shts': 'significant_height_of_total_swell', 
               'shww': 'significant_height_of_wind_waves', 'swh1': 'significant_wave_height_of_first_swell_partition', 
               'swh2': 'significant_wave_height_of_second_swell_partition', 'swh3': 'significant_wave_height_of_third_swell_partition', 
               'src': 'skin_reservoir_content', 'skt': 'skin_temperature', 'slor': 'slope_of_sub_gridscale_orography', 'asn': 'snow_albedo', 
               'rsn': 'snow_density', 'sd': 'snow_depth', 'es': 'snow_evaporation', 'sf': 'snowfall', 'smlt': 'snowmelt', 'stl1': 'soil_temperature_level_1', 
               'stl2': 'soil_temperature_level_2', 'stl3': 'soil_temperature_level_3', 'stl4': 'soil_temperature_level_4', 'slt': 'soil_type', 
               'ciwc': 'specific_cloud_ice_water_content', 'clwc': 'specific_cloud_liquid_water_content', 'q': 'specific_humidity', 
               'sdfor': 'standard_deviation_of_filtered_subgrid_orography', 'sdor': 'standard_deviation_of_orography', 'ssro': 'sub_surface_runoff', 
               'slhf': 'surface_latent_heat_flux', 'ssr': 'surface_net_solar_radiation', 'ssrc': 'surface_net_solar_radiation_clear_sky', 
               'str': 'surface_net_thermal_radiation', 'strc': 'surface_net_thermal_radiation_clear_sky', 'sp': 'surface_pressure', 'sro': 'surface_runoff', 
               'sshf': 'surface_sensible_heat_flux', 'ssrdc': 'surface_solar_radiation_downward_clear_sky', 'ssrd': 'surface_solar_radiation_downwards', 
               'strdc': 'surface_thermal_radiation_downward_clear_sky', 'strd': 'surface_thermal_radiation_downwards', 't': 'temperature', 
               'tsn': 'temperature_of_snow_layer', 'tisr': 'toa_incident_solar_radiation', 'tsr': 'top_net_solar_radiation', 
               'tsrc': 'top_net_solar_radiation_clear_sky', 'ttr': 'top_net_thermal_radiation', 'ttrc': 'top_net_thermal_radiation_clear_sky', 
               'tcc': 'total_cloud_cover', 'tciw': 'total_column_cloud_ice_water', 'tclw': 'total_column_cloud_liquid_water', 'tco3': 'total_column_ozone', 
               'tcrw': 'total_column_rain_water', 'tcsw': 'total_column_snow_water', 'tcslw': 'total_column_supercooled_liquid_water', 'tcw': 'total_column_water', 
               'tcwv': 'total_column_water_vapour', 'tp': 'total_precipitation', 'fdir': 'total_sky_direct_solar_radiation_at_surface', 'totalx': 'total_totals_index', 
               'tplb': 'trapping_layer_base_height', 'tplt': 'trapping_layer_top_height', 'tvh': 'type_of_high_vegetation', 'tvl': 'type_of_low_vegetation', 
               'u': 'u_component_of_wind', 'ust': 'u_component_stokes_drift', 'aluvd': 'uv_visible_albedo_for_diffuse_radiation', 
               'aluvp': 'uv_visible_albedo_for_direct_radiation', 'v': 'v_component_of_wind', 'vst': 'v_component_stokes_drift', 
               'viiw': 'vertical_integral_of_divergence_of_cloud_frozen_water_flux', 'vilw': 'vertical_integral_of_divergence_of_cloud_liquid_water_flux', 
               'vigd': 'vertical_integral_of_divergence_of_geopotential_flux', 'viked': 'vertical_integral_of_divergence_of_kinetic_energy_flux', 
               'vimad': 'vertical_integral_of_divergence_of_mass_flux', 'vimdf': 'vertical_integral_of_divergence_of_moisture_flux', 
               'viozd': 'vertical_integral_of_divergence_of_ozone_flux', 'vithed': 'vertical_integral_of_divergence_of_thermal_energy_flux', 
               'vited': 'vertical_integral_of_divergence_of_total_energy_flux', 'viiwe': 'vertical_integral_of_eastward_cloud_frozen_water_flux', 
               'vilwe': 'vertical_integral_of_eastward_cloud_liquid_water_flux', 'vige': 'vertical_integral_of_eastward_geopotential_flux', 
               'vithee': 'vertical_integral_of_eastward_heat_flux', 'vikee': 'vertical_integral_of_eastward_kinetic_energy_flux', 
               'vimae': 'vertical_integral_of_eastward_mass_flux', 'vioze': 'vertical_integral_of_eastward_ozone_flux', 
               'vitee': 'vertical_integral_of_eastward_total_energy_flux', 'viwve': 'vertical_integral_of_eastward_water_vapour_flux', 
               'viec': 'vertical_integral_of_energy_conversion', 'vike': 'vertical_integral_of_kinetic_energy', 'vima': 'vertical_integral_of_mass_of_atmosphere', 
               'vimat': 'vertical_integral_of_mass_tendency', 'viiwn': 'vertical_integral_of_northward_cloud_frozen_water_flux', 
               'vilwn': 'vertical_integral_of_northward_cloud_liquid_water_flux', 'vign': 'vertical_integral_of_northward_geopotential_flux', 
               'vithen': 'vertical_integral_of_northward_kinetic_energy_flux', 'viman': 'vertical_integral_of_northward_mass_flux', 
               'viozn': 'vertical_integral_of_northward_ozone_flux', 'viten': 'vertical_integral_of_northward_total_energy_flux', 
               'viwvn': 'vertical_integral_of_northward_water_vapour_flux', 'vipie': 'vertical_integral_of_potential_and_internal_energy', 
               'vipile': 'vertical_integral_of_potential_internal_and_latent_energy', 'vit': 'vertical_integral_of_temperature', 
               'vithe': 'vertical_integral_of_thermal_energy', 'vitoe': 'vertical_integral_of_total_energy', 'w': 'vertical_velocity', 
               'vimd': 'vertically_integrated_moisture_divergence', 'swvl1': 'volumetric_soil_water_layer_1', 'swvl2': 'volumetric_soil_water_layer_2', 
               'swvl3': 'volumetric_soil_water_layer_3', 'swvl4': 'volumetric_soil_water_layer_4', 'wdw': 'wave_spectral_directional_width', 
               'dwps': 'wave_spectral_directional_width_for_swell', 'dwww': 'wave_spectral_directional_width_for_wind_waves', 'wsk': 'wave_spectral_kurtosis', 
               'wsp': 'wave_spectral_peakedness', 'wss': 'wave_spectral_skewness', 'deg0l': 'zero_degree_level'}