[package]
name = "aisdb-receiver"
version = "0.0.1"
edition = "2021"
authors = [ "MERIDIAN // Matt Smith matthew.smith@dal.ca",]
readme = "../readme.rst"
description = "AISDB Receiver"
homepage = "https://aisdb.meridian.cs.dal.ca/"
documentation = "https://aisdb.meridian.cs.dal.ca/doc/readme.html"
license-file = "../license.txt"

[lib]

[[bin]]
name = "aisdb-receiver"
path = "src/receiver.rs"


[dependencies]
aisdb-lib = { path = "../aisdb_lib" }
mproxy-client = { version = "0.1" }
mproxy-server = { version = "0.1" }
mproxy-forward = { features = ["tls"], version = "0.1" }
mproxy-reverse = { version = "0.1" }

nmea-parser = { version = "0.10" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
tungstenite = {version = "0.20", features = ["rustls-tls-webpki-roots"]}
pico-args = { version = "0.5", features = [ "eq-separator",]}
