[package]
name = "server"
version = "0.1.0"
edition = "2021"


[dependencies]
dispatch = {path = "../dispatch"}

[dependencies.pico-args]
version = "0.5.0"
features = [ "eq-separator",]

[dev-dependencies]
client = {path = "../client"}
testconfig = {path = "../testconfig"}
