CREATE TABLE coarsetype_ref (
    coarse_type integer,
    coarse_type_txt character varying(75),
    PRIMARY KEY (coarse_type)
);
INSERT INTO coarsetype_ref VALUES(20,'Wing In Grnd');
INSERT INTO coarsetype_ref VALUES(21,'Wing In Grnd, hazardous category A');
INSERT INTO coarsetype_ref VALUES(22,'Wing In Grnd, hazardous category B');
INSERT INTO coarsetype_ref VALUES(23,'Wing In Grnd, hazardous category C');
INSERT INTO coarsetype_ref VALUES(24,'Wing In Grnd, hazardous category D');
INSERT INTO coarsetype_ref VALUES(25,'Wing In Grnd');
INSERT INTO coarsetype_ref VALUES(26,'Wing In Grnd');
INSERT INTO coarsetype_ref VALUES(27,'Wing In Grnd');
INSERT INTO coarsetype_ref VALUES(28,'Wing In Grnd');
INSERT INTO coarsetype_ref VALUES(29,'Wing In Grnd');
INSERT INTO coarsetype_ref VALUES(30,'Fishing');
INSERT INTO coarsetype_ref VALUES(31,'Towing');
INSERT INTO coarsetype_ref VALUES(32,'Towing - length >200m or breadth >25m');
INSERT INTO coarsetype_ref VALUES(33,'Dredger');
INSERT INTO coarsetype_ref VALUES(34,'Dive Vessel');
INSERT INTO coarsetype_ref VALUES(35,'Military Ops');
INSERT INTO coarsetype_ref VALUES(36,'Sailing Vessel');
INSERT INTO coarsetype_ref VALUES(37,'Pleasure Craft');
INSERT INTO coarsetype_ref VALUES(38,'Reserved for future use');
INSERT INTO coarsetype_ref VALUES(39,'Reserved for future use');
INSERT INTO coarsetype_ref VALUES(40,'High speed craft');
INSERT INTO coarsetype_ref VALUES(41,'High speed craft, hazardous category A');
INSERT INTO coarsetype_ref VALUES(42,'High speed craft, hazardous category B');
INSERT INTO coarsetype_ref VALUES(43,'High speed craft, hazardous category C');
INSERT INTO coarsetype_ref VALUES(44,'High speed craft, hazardous category D');
INSERT INTO coarsetype_ref VALUES(45,'High speed craft');
INSERT INTO coarsetype_ref VALUES(46,'High speed craft');
INSERT INTO coarsetype_ref VALUES(47,'High speed craft');
INSERT INTO coarsetype_ref VALUES(48,'High speed craft');
INSERT INTO coarsetype_ref VALUES(49,'High speed craft');
INSERT INTO coarsetype_ref VALUES(50,'Pilot vessel');
INSERT INTO coarsetype_ref VALUES(51,'SAR');
INSERT INTO coarsetype_ref VALUES(52,'Tug');
INSERT INTO coarsetype_ref VALUES(53,'Port Tender');
INSERT INTO coarsetype_ref VALUES(54,'Anti-Pollution');
INSERT INTO coarsetype_ref VALUES(55,'Law Enforce');
INSERT INTO coarsetype_ref VALUES(56,'Spare - local vessels');
INSERT INTO coarsetype_ref VALUES(57,'Spare - local vessels');
INSERT INTO coarsetype_ref VALUES(58,'Medical Trans)');
INSERT INTO coarsetype_ref VALUES(59,'Ships and aircraft of States not parties to an armed conflict');
INSERT INTO coarsetype_ref VALUES(60,'Passenger');
INSERT INTO coarsetype_ref VALUES(61,'Passenger, hazardous category A');
INSERT INTO coarsetype_ref VALUES(62,'Passenger, hazardous category B');
INSERT INTO coarsetype_ref VALUES(63,'Passenger, hazardous category C');
INSERT INTO coarsetype_ref VALUES(64,'Passenger, hazardous category D');
INSERT INTO coarsetype_ref VALUES(65,'Passenger');
INSERT INTO coarsetype_ref VALUES(66,'Passenger');
INSERT INTO coarsetype_ref VALUES(67,'Passenger');
INSERT INTO coarsetype_ref VALUES(68,'Passenger');
INSERT INTO coarsetype_ref VALUES(69,'Passenger');
INSERT INTO coarsetype_ref VALUES(70,'Cargo');
INSERT INTO coarsetype_ref VALUES(71,'Cargo, hazardous category A');
INSERT INTO coarsetype_ref VALUES(72,'Cargo, hazardous category B');
INSERT INTO coarsetype_ref VALUES(73,'Cargo, hazardous category C');
INSERT INTO coarsetype_ref VALUES(74,'Cargo, hazardous category D');
INSERT INTO coarsetype_ref VALUES(75,'Cargo');
INSERT INTO coarsetype_ref VALUES(76,'Cargo');
INSERT INTO coarsetype_ref VALUES(77,'Cargo');
INSERT INTO coarsetype_ref VALUES(78,'Cargo');
INSERT INTO coarsetype_ref VALUES(79,'Cargo');
INSERT INTO coarsetype_ref VALUES(80,'Tanker');
INSERT INTO coarsetype_ref VALUES(81,'Tanker, hazardous category A');
INSERT INTO coarsetype_ref VALUES(82,'Tanker, hazardous category B');
INSERT INTO coarsetype_ref VALUES(83,'Tanker, hazardous category C');
INSERT INTO coarsetype_ref VALUES(84,'Tanker, hazardous category D');
INSERT INTO coarsetype_ref VALUES(85,'Tanker');
INSERT INTO coarsetype_ref VALUES(86,'Tanker');
INSERT INTO coarsetype_ref VALUES(87,'Tanker');
INSERT INTO coarsetype_ref VALUES(88,'Tanker');
INSERT INTO coarsetype_ref VALUES(89,'Tanker');
INSERT INTO coarsetype_ref VALUES(90,'Other');
INSERT INTO coarsetype_ref VALUES(91,'Other, hazardous category A');
INSERT INTO coarsetype_ref VALUES(92,'Other, hazardous category B');
INSERT INTO coarsetype_ref VALUES(93,'Other, hazardous category C');
INSERT INTO coarsetype_ref VALUES(94,'Other, hazardous category D');
INSERT INTO coarsetype_ref VALUES(95,'Other');
INSERT INTO coarsetype_ref VALUES(96,'Other');
INSERT INTO coarsetype_ref VALUES(97,'Other');
INSERT INTO coarsetype_ref VALUES(98,'Other');
INSERT INTO coarsetype_ref VALUES(99,'Other');
INSERT INTO coarsetype_ref VALUES(100,'Unknown');
