CREATE TABLE coarsetype_ref (
    coarse_type integer,
    coarse_type_txt character varying(75),
    PRIMARY KEY (coarse_type)
);
INSERT INTO coarsetype_ref VALUES(20,'Wing in ground craft');
INSERT INTO coarsetype_ref VALUES(21,'Wing in ground craft, hazardous category A');
INSERT INTO coarsetype_ref VALUES(22,'Wing in ground craft, hazardous category B');
INSERT INTO coarsetype_ref VALUES(23,'Wing in ground craft, hazardous category C');
INSERT INTO coarsetype_ref VALUES(24,'Wing in ground craft, hazardous category D');
INSERT INTO coarsetype_ref VALUES(25,'Wing in ground craft');
INSERT INTO coarsetype_ref VALUES(26,'Wing in ground craft');
INSERT INTO coarsetype_ref VALUES(27,'Wing in ground craft');
INSERT INTO coarsetype_ref VALUES(28,'Wing in ground craft');
INSERT INTO coarsetype_ref VALUES(29,'Wing in ground craft');
INSERT INTO coarsetype_ref VALUES(30,'Fishing');
INSERT INTO coarsetype_ref VALUES(31,'Towing');
INSERT INTO coarsetype_ref VALUES(32,'Towing - length >200m or breadth >25m');
INSERT INTO coarsetype_ref VALUES(33,'Engaged in dredging or underwater operations');
INSERT INTO coarsetype_ref VALUES(34,'Engaged in diving operations');
INSERT INTO coarsetype_ref VALUES(35,'Engaged in military operations');
INSERT INTO coarsetype_ref VALUES(36,'Sailing');
INSERT INTO coarsetype_ref VALUES(37,'Pleasure craft');
INSERT INTO coarsetype_ref VALUES(38,'Reserved for future use');
INSERT INTO coarsetype_ref VALUES(39,'Reserved for future use');
INSERT INTO coarsetype_ref VALUES(40,'High speed craft');
INSERT INTO coarsetype_ref VALUES(41,'High speed craft, hazardous category A');
INSERT INTO coarsetype_ref VALUES(42,'High speed craft, hazardous category B');
INSERT INTO coarsetype_ref VALUES(43,'High speed craft, hazardous category C');
INSERT INTO coarsetype_ref VALUES(44,'High speed craft, hazardous category D');
INSERT INTO coarsetype_ref VALUES(45,'High speed craft');
INSERT INTO coarsetype_ref VALUES(46,'High speed craft');
INSERT INTO coarsetype_ref VALUES(47,'High speed craft');
INSERT INTO coarsetype_ref VALUES(48,'High speed craft');
INSERT INTO coarsetype_ref VALUES(49,'High speed craft');
INSERT INTO coarsetype_ref VALUES(50,'Pilot vessel');
INSERT INTO coarsetype_ref VALUES(51,'Search and rescue vessels');
INSERT INTO coarsetype_ref VALUES(52,'Tugs');
INSERT INTO coarsetype_ref VALUES(53,'Port tenders');
INSERT INTO coarsetype_ref VALUES(54,'Vessels with anti-pollution facilities or equipment');
INSERT INTO coarsetype_ref VALUES(55,'Law enforcement vessels');
INSERT INTO coarsetype_ref VALUES(56,'Spare for assignments to local vessels');
INSERT INTO coarsetype_ref VALUES(57,'Spare for assignments to local vessels');
INSERT INTO coarsetype_ref VALUES(58,'Medical transports (1949 Geneva convention)');
INSERT INTO coarsetype_ref VALUES(59,'Ships and aircraft of States not parties to an armed conflict');
INSERT INTO coarsetype_ref VALUES(60,'Passenger ships');
INSERT INTO coarsetype_ref VALUES(61,'Passenger ships, hazardous category A');
INSERT INTO coarsetype_ref VALUES(62,'Passenger ships, hazardous category B');
INSERT INTO coarsetype_ref VALUES(63,'Passenger ships, hazardous category C');
INSERT INTO coarsetype_ref VALUES(64,'Passenger ships, hazardous category D');
INSERT INTO coarsetype_ref VALUES(65,'Passenger ships');
INSERT INTO coarsetype_ref VALUES(66,'Passenger ships');
INSERT INTO coarsetype_ref VALUES(67,'Passenger ships');
INSERT INTO coarsetype_ref VALUES(68,'Passenger ships');
INSERT INTO coarsetype_ref VALUES(69,'Passenger ships');
INSERT INTO coarsetype_ref VALUES(70,'Cargo ships');
INSERT INTO coarsetype_ref VALUES(71,'Cargo ships, hazardous category A');
INSERT INTO coarsetype_ref VALUES(72,'Cargo ships, hazardous category B');
INSERT INTO coarsetype_ref VALUES(73,'Cargo ships, hazardous category C');
INSERT INTO coarsetype_ref VALUES(74,'Cargo ships, hazardous category D');
INSERT INTO coarsetype_ref VALUES(75,'Cargo ships');
INSERT INTO coarsetype_ref VALUES(76,'Cargo ships');
INSERT INTO coarsetype_ref VALUES(77,'Cargo ships');
INSERT INTO coarsetype_ref VALUES(78,'Cargo ships');
INSERT INTO coarsetype_ref VALUES(79,'Cargo ships');
INSERT INTO coarsetype_ref VALUES(80,'Tankers');
INSERT INTO coarsetype_ref VALUES(81,'Tankers, hazardous category A');
INSERT INTO coarsetype_ref VALUES(82,'Tankers, hazardous category B');
INSERT INTO coarsetype_ref VALUES(83,'Tankers, hazardous category C');
INSERT INTO coarsetype_ref VALUES(84,'Tankers, hazardous category D');
INSERT INTO coarsetype_ref VALUES(85,'Tankers');
INSERT INTO coarsetype_ref VALUES(86,'Tankers');
INSERT INTO coarsetype_ref VALUES(87,'Tankers');
INSERT INTO coarsetype_ref VALUES(88,'Tankers');
INSERT INTO coarsetype_ref VALUES(89,'Tankers');
INSERT INTO coarsetype_ref VALUES(90,'Other');
INSERT INTO coarsetype_ref VALUES(91,'Other, hazardous category A');
INSERT INTO coarsetype_ref VALUES(92,'Other, hazardous category B');
INSERT INTO coarsetype_ref VALUES(93,'Other, hazardous category C');
INSERT INTO coarsetype_ref VALUES(94,'Other, hazardous category D');
INSERT INTO coarsetype_ref VALUES(95,'Other');
INSERT INTO coarsetype_ref VALUES(96,'Other');
INSERT INTO coarsetype_ref VALUES(97,'Other');
INSERT INTO coarsetype_ref VALUES(98,'Other');
INSERT INTO coarsetype_ref VALUES(99,'Other');
INSERT INTO coarsetype_ref VALUES(100,'Unknown');
