name: API Doc Generation

on: workflow_dispatch

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install system dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libssl-dev openssl pkg-config zlib1g-dev clang

      - name: Add wasm target
        run: rustup target add wasm32-unknown-unknown

      - name: Install wasm-pack
        run: |
          cargo install --locked wasm-pack wasm-bindgen-cli wasm-opt
          wasm-pack --version

      - name: Build AISdb
        run: |
          python -m venv .venv
          source .venv/bin/activate || exit 1
          python -m pip install --upgrade pip || exit 1
          python -m pip install maturin || exit 1
          maturin develop || exit 1

      - name: Install dependencies for API docs
        run: |
          source .venv/bin/activate || exit 1
          python -m pip install sphinx sphinx-rtd-theme matplotlib joblib || exit 1

      - name: Build docs
        run: |
          source .venv/bin/activate || exit 1
          sphinx-apidoc --separate --force --implicit-namespaces --module-first -o docs/source/api aisdb aisdb/tests/* || exit 1
          python -m sphinx -a -j auto -b=html docs/source docs/dist_sphinx || exit 1

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/dist_sphinx

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Clean up
        run: |
          rm -rf docs/dist_sphinx
          rm -rf .venv
