name: Pipeline

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

env:
  pguser: "postgres"
  pghost: "127.0.0.1"
  pgpass: ${{ secrets.PGPASS }}

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install sphinx
          python -m pip install sphinx-rtd-theme

      - name: Build docs
        run: |
          sphinx-apidoc --separate --force --implicit-namespaces --module-first --no-toc -o docs/source/api aisdb aisdb/tests/*
          python -m sphinx -a -j auto -q -b=html docs/source docs/dist_sphinx

      - name: Upload docs to gh-pages branch
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git clone --branch gh-pages --single-branch https://github.com/AISViz/AISdb.git gh-pages
          cp -r docs/dist_sphinx/* gh-pages/
          cd gh-pages
          git add .
          git commit -m "Update docs"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/AISViz/AISdb.git gh-pages

      - name: Clean Up
        run: |
          rm -rf gh-pages
          rm -rf docs/dist_sphinx




