name: Installation

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Rust Toolchain
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > install-rust.sh
        sh install-rust.sh -q -y
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Create and Activate Python Virtual Environment
      run: |
        python -m venv AISdb
        source ./AISdb/bin/activate

    - name: Install Maturin
      run: python -m pip install --upgrade maturin[patchelf]

    - name: Install wasm-pack
      run: |
        cargo install --locked wasm-pack --verbose
        cargo install --locked wasm-bindgen-cli --verbose
        cargo install --locked wasm-opt --verbose
        wasm-pack --version
        wasm-bindgen-cli --version
        wasm-opt --version

    - name: Build and Install aisdb
      run: |
        source ./AISdb/bin/activate
        maturin develop --release --extras=test,docs

    - name: Verify Installation
      run: |
        source ./AISdb/bin/activate
        python -c "import aisdb; assert aisdb.__version__ >= '1.7.1', f'Unexpected aisdb version: {aisdb.__version__}'"
